create table sutdy_details(id int primary key ,name varchar(10),subj varchar(20),location varchar(13),dept_id int);
select * from sutdy_details;
insert into sutdy_details values(01,'muni','maths','neltur','123');
insert into sutdy_details values('02','lakshmi','sci','gudur','124');
insert into sutdy_details values(03,'deep','tel','nlr','125');
insert into sutdy_details values('04','karunakar','maths','kota','126');
insert into sutdy_details values('05','komala','eng','hyd','126');
insert into sutdy_details values('06','prasana','eng','nlr','127');
insert into sutdy_details values('07','kavitha','teg','gudur','128');
select * from sutdy_details where id=01 ;
select id,name from sutdy_details where subj='maths';
select * from sutdy_details where id>1 or id>8;
select * from sutdy_details where id<7 and id>1;
select * from sutdy_details where id<>3;
select id,name,subj from sutdy_details where id<>4;
select * from sutdy_details where id between 1 and 2;
select name from sutdy_details where dept_id between 123 and 125;
select id,name,subj from sutdy_details where dept_id between 123 and 128;
select * from sutdy_details where id between 1 and 4;
select * from sutdy_details where location between 'kota'and 'kota';
select * from sutdy_details where name between 'muni'and 'muni';
select * from sutdy_details where id not between 1 and 4;
select name,location,subj from sutdy_details where dept_id not between 125 and 126;
select * from sutdy_details where dept_id not between 126 and 127;
select * from sutdy_details where subj not between 'maths'and 'teg';
select id,name,subj,location from sutdy_details where location not between 'nlr'and 'nlr';
select * from sutdy_details where subj between 'maths' and 'maths' and dept_id in(123,124,125);
select * from sutdy_details where dept_id between 123 and 126 and id in(1,2,3);
select * from sutdy_details where id not between 3 and 5 and dept_id in(123,125,127);
select count(id)from sutdy_details;
select count(location)from sutdy_details;
select sum(id)from sutdy_details;
select max(name)from sutdy_details;
select min (name)from sutdy_details;
select avg(id)from sutdy_details;
select subj,count(subj)from sutdy_details group by subj;
select id,name,count(name)from sutdy_details where id>1 group by id,name order by id asc;
select *, max(id) from sutdy_details group by id;
select name,subj,count(subj)as count_subj from sutdy_details group by name,subj;
select subj,count(subj)as count_subj from sutdy_details group by subj;
select *,min(id)from sutdy_details where id=5 group by id;
select name,id,subj,max(name)from sutdy_details where id<5 group by id;
select * from sutdy_details where name like'%';
select * from sutdy_details where name like '____';
select * from sutdy_details where location like 'n%';
select * from sutdy_details where subj like 'm%s';
select * from sutdy_details where name like 'k%'or name like'm%';
select * from sutdy_details where subj like '%g' and subj like '%g';
select * from sutdy_details where name like 'm__i';
create table employee_details(emp_id int,emp_name varchar(20),salary int);
select * from employee_details;
insert into employee_details values(123,'abcd','15000');
insert into employee_details values(124,'cde','20000');
insert into employee_details values(125,'def','25000');
insert into employee_details values(126,'ijk','15000');
insert into employee_details values(127,'pqr','20000');
insert into employee_details values(128,'kol','35000');
insert into employee_details values(129,'mnl','30000');
insert into employee_details values(130,'xyz','45000');
insert into employee_details values(131,'ghl','40000');
delete from employee_details where  emp_name=abcd 15000;
select * from employee_details;
delete  from employee_details;
select sutdy_details.name,sutdy_details.dept_id,sutdy_details.subj,sutdy_details.location,employee_details.emp_name,employee_details.salary from sutdy_details join employee_details on sutdy_details.id=employee_details.emp_id;
select name,dept_id,subj,emp_name,salary from sutdy_details inner join employee_details on sutdy_details.id=employee_details.emp_id group by name,dept_id,subj,emp_name,salary;
select * from employee_details where salary<(select max(salary)from employee_details);
select * from sutdy_details where dept_id>(select min(dept_id)from sutdy_details);
select id from sutdy_details where id < (select max(id)from sutdy_details );
select * from employee_details where salary<(select  max(salary) from employee_details );
select * from employee_details where (emp_id,emp_name) in(select emp_id,salary,min(emp_id) from employee_details group by emp_id,salary);
select emp_name from employee_details where emp_id='123' in (select emp_id from dept_details);
SELECT *, row_number()over(partition by emp_name order by salary asc)as row_num from employee_details; 
select dept_id,name,subj,row_number()over(partition by subj order by subj asc)as row_num from sutdy_details;   
select *,row_number()over(partition by location  order by location asc)row_num from sutdy_details;
select name ,row_number()over(partition by subj )as row_num from sutdy_details;
select*,row_number()over(order by subj)as row_num from sutdy_details;
select*,rank()over(order by location )as rank_num from sutdy_details;
select *,rank()over(partition by location order by location asc)as rank_num from sutdy_details;
select*,rank()over(order by location)as rank_num from sutdy_details;
select*,dense_rank()over(order by subj asc)as des_num from sutdy_details;
select*,dense_rank()over(partition by subj)as des_num from sutdy_details;
select*,dense_rank()over(partition by location order by subj asc)from sutdy_details;
select*,first_value(name)over(partition by subj)as lead_num from sutdy_details;
select name,first_value(name)over(order by subj)as num from sutdy_details;
select*,last_value(name)over(order by name)as num from sutdy_details;
select *,count(name)over(order by name)as num from sutdy_details;
select * ,count(name)over(partition by name)as num from sutdy_details;
select *,lead(id)over(partition by id)as num from sutdy_details;
select name,id,ntile(id)over(partition by id)as num from sutdy_details;